FROM python:3.10 AS webautomation


WORKDIR /TESTING/

RUN python3.10 -m venv venv 

RUN python -m pip install --upgrade pip

COPY requirements.txt requirements.txt
COPY . .
RUN pip install -r requirements.txt

CMD ["python","-m","pytest","tests/test_search.py","--alluredir=reports","--host","chrome","--remote"]
